### ISSUE TITLE
ModuleNotFoundError: No module named 'src.utils.tab_rl'

### ISSUE THREAD

**Issue by liuqi8827** [SwordShieldMouse/back-it-up#19]
Hi,

Thanks for your interesting and useful code.

I download the project. 
However, when I run `./experiments/continuous_switch_stay/run.sh`
The error occurred:
```
Traceback (most recent call last):
  File "/home/back-it-up/experiments/continuous_switch_stay/run.py", line 12, in <module>
    from helper import *
  File "/home/back-it-up/experiments/continuous_switch_stay/helper.py", line 14, in <module>
    import env
  File "/home/back-it-up/experiments/continuous_switch_stay/env.py", line 9, in <module>
    import src.utils.tab_rl as tab_rl
ModuleNotFoundError: No module named 'src.utils.tab_rl'
```

I found that there is no such file `tab_rl.py` in the folder `src/utils/`

Can you give some suggestions?

Thanks a lot!

**Comment by SwordShieldMouse** [comment]
[tab_rl.txt](https://github.com/SwordShieldMouse/back-it-up/files/9597271/tab_rl.txt)

Does this file work?

**Comment by liuqi8827** [comment]
Thanks for your quick reply.

It works well.
